# Generated by Django 2.1.7 on 2019-02-21 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=15)),
                ('correo', models.EmailField(blank=True, max_length=254)),
                ('mensaje', models.TextField()),
            ],
        ),
    ]
